name: py3ssn
channels:
  - pytorch
  - conda-forge
  - defaults
  - simpleitk
  - nvidia
dependencies:
  - pytorch
  - torchvision
  - pytorch-cuda
  - matplotlib
  - jupyter
  - numpy
  - pandas
  - pip
  - python
  - scipy
  - simpleitk
  # - svgutils
  - tabulate
  - tqdm
  - tensorboard
  - pip:
    - laplace-torch
    # - logbesselk
